[package]
name = "fetch-http-status"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://crates.io/crates/reqwest
reqwest = { version = "0.11", features = ["blocking"] }
rayon = "1"
